services:
    forumhulp.emailonbirthday.lang_manager:
        class: forumhulp\emailonbirthday\lang_manager\manager
        arguments:
            - %core.root_path%
    forumhulp.emailonbirthday.listener:
        class: forumhulp\emailonbirthday\event\listener
        arguments:
            - @controller.helper
        tags:
            - { name: event.listener }
    forumhulp.cron.emailonbirthday:
        class: forumhulp\emailonbirthday\cron\task\core\birthday
        arguments:
            - %core.root_path%
            - %core.php_ext%
            - @config
            - @user
            - @dbal.conn
            - @log
            - @forumhulp.emailonbirthday.lang_manager
            - @service_container
        calls:
            - [set_name, [forumhulp.cron.emailonbirthday]]
        tags:
            - { name: cron.task }
